### ISSUE TITLE
Possible bug with mixin parameters (?)

### ISSUE THREAD

**Issue by humhue** [manuthebyte/template-forge-1.8.9#3]
I've tried to mixin into WorldRenderer.putPosition(double x, double y, double z), but x, y, z appear to lose their decimal parts when intercepted by the mixin, although the game logic retains and uses the full precision values. This issue does not occur in a non-Forge environment using a tweaker client (https://github.com/PaceCodes/Mixin-Tutorial) and I've in fact verified that the very same mixin code for the WorldRenderer works correctly and can read and modify the full precision values using the tweaker client. I've also checked the parameters using MCP 1.8.8 and confirmed that the three double values CAN have decimal parts (as is the case with grass and other blocks using offsets).

Expected Behavior:
The mixin should capture and handle the full precision double values, consistent with the game logic.

Actual Behavior:
The mixin captures only the integer parts of the double values, leading to an apparent (because the game internally still uses the original values) precision loss.

Steps to reproduce:
try to mixin into WorldRenderer and check x, y, z.

```
package net.example;

import net.minecraft.client.renderer.WorldRenderer;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(WorldRenderer.class)
public class MixinWorldRenderer {
    @Inject(method = "putPosition", at = @At("HEAD"))
    private void onPutPosition(double x, double y, double z, CallbackInfo ci) {
        if (x % 1 != 0) { System.out.println("yes x"); }
        else if (y % 1 != 0) { System.out.println("yes y"); }
        else if (z % 1 != 0) { System.out.println("yes z"); }
        else { System.out.println("none"); }
    }
}
```
a lot of `none` get printed in the terminal, but not even one `yes`.
Or using assert:
```
private void onPutPosition(double x, double y, double z, CallbackInfo ci) {
    assert x % 1 == 0;
    assert y % 1 == 0;
    assert z % 1 == 0;
}
```

Additionally, this just doesn't make sense... it looks like the mixin has only access to the integer part, because even when I try to overwrite the original parameters (using a flag, instance variables and ModifyVariable for each of the parameters), with other doubles without decimal parts, the offsets are still unchanged from the original ones, and retain their decimal parts (i.e in game grass offsets are still present), while this doesn't happen when I use the mixin with the tweaker client project linked earlier.
I hope I'm just missing something obvious but I have checked in MCP and with the tweaker client and I've tried to do this simple thing for days now.

**Comment by manuthebyte** [comment]
Hey! This seems like a really odd issue, I've never had something like this happen to me ever before..
The only thing I can imagine is - if you think about how old this version actually is - that Forge has done some weird tinkering that triggers this issue. 

Did you take a look inside the original decompiled `WorldRenderer.java` file? Maybe something is to be found there that explains this issue.

**Comment by humhue** [comment]
I've used MCP to read the decompiled code, make some changes, and rebuild it, and it worked as expected, i.e, offsets are there (but I'm able to turn them off), doubles have decimal parts etc.
Anyway, I was able to make this work in 1.7.10. The reason why it doesn't work in 1.8.9 is either a forge bug, or an oversight on my part.
In any case, I don't think it has to do anything with the template, so I think you can close this issue if you want.
Thank you for the reply :)

**Comment by manuthebyte** [comment]
I think so as well. If some other unexpected behaviour happens, please open a new issue :)
